<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Thoughtfully selected products, delivered across Bangladesh.">
    <title>{{ config('store.name') }} — Everyday, Elevated</title>
    <link rel="icon" type="image/png" href="{{ asset('favicon.png') }}">
    <link rel="apple-touch-icon" href="{{ asset('images/al-nas-logo.jpg') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
    @vite(['resources/css/app.css','resources/js/app.js'])
</head>
<body class="grain antialiased">
<div class="bg-[#081426] px-4 py-2.5 text-center text-xs font-medium tracking-[.18em] text-white">CASH ON DELIVERY · NATIONWIDE SHIPPING</div>
<header class="sticky top-0 z-30 border-b border-black/5 bg-[#f7f5f0]/90 backdrop-blur-xl">
    <div class="mx-auto flex h-28 max-w-7xl items-center justify-between px-5 sm:h-32 lg:px-8">
        <a href="#" aria-label="Al-Nas home" class="rounded-full"><img src="{{ config('store.logo') }}" alt="Al-Nas logo" class="h-24 w-24 rounded-full object-contain shadow-sm ring-1 ring-[#c8a34f]/40 sm:h-28 sm:w-28"></a>
        <nav class="hidden items-center gap-8 text-sm md:flex"><a href="#shop" class="hover:text-amber-700">Shop</a><a href="#story" class="hover:text-amber-700">Our Story</a><a href="{{ route('store.track') }}" class="hover:text-amber-700">Track Order</a><a href="{{ config('store.facebook') }}" target="_blank" rel="noopener" class="hover:text-amber-700">Facebook</a></nav>
        <button data-open-cart class="relative flex items-center gap-2 rounded-full border border-stone-300 px-4 py-2 text-sm font-semibold">Bag <span data-cart-count class="grid h-5 w-5 place-items-center rounded-full bg-[#081426] text-[10px] text-white">0</span></button>
    </div>
</header>
<main>
    <section class="mx-auto grid min-h-[78vh] max-w-7xl gap-10 px-5 py-12 lg:grid-cols-[1.02fr_.98fr] lg:items-center lg:px-8 lg:py-16">
        <div class="max-w-2xl"><p class="mb-5 text-xs font-bold tracking-[.25em] text-amber-700">THE NEW COLLECTION · 2026</p><h1 class="font-display text-6xl font-semibold leading-[.93] tracking-tight sm:text-7xl lg:text-[92px]">Everyday,<br><em class="font-medium text-[#c79a42]">elevated.</em></h1><p class="mt-7 max-w-lg text-lg leading-8 text-stone-600">Thoughtfully selected essentials made to bring beauty, comfort and confidence to your everyday life.</p><div class="mt-9 flex flex-wrap gap-3"><a href="#shop" class="rounded-full bg-[#081426] px-7 py-3.5 text-sm font-bold text-white transition hover:bg-[#142744]">Shop the collection</a><a href="{{ config('store.facebook') }}" target="_blank" class="rounded-full border border-stone-300 px-7 py-3.5 text-sm font-bold hover:bg-white">Visit Facebook</a></div><div class="mt-12 flex gap-8 text-sm"><div><b class="block text-lg">100%</b><span class="text-stone-500">Quality checked</span></div><div><b class="block text-lg">64</b><span class="text-stone-500">District delivery</span></div><div><b class="block text-lg">COD</b><span class="text-stone-500">Secure payment</span></div></div></div>
        <div class="relative min-h-[520px] overflow-hidden rounded-[2rem] bg-stone-200"><img src="{{ $settings->fresh_image }}" alt="{{ $settings->fresh_title }}" class="absolute inset-0 h-full w-full object-cover"><div class="absolute bottom-5 left-5 rounded-2xl bg-white/90 p-4 backdrop-blur"><p class="text-xs uppercase tracking-widest text-stone-500">{{ $settings->fresh_label }}</p><p class="font-display text-2xl font-semibold">{{ $settings->fresh_title }}</p></div></div>
    </section>
    <section id="shop" class="bg-white py-20 sm:py-24"><div class="mx-auto max-w-7xl px-5 lg:px-8"><div class="reveal mb-10 flex items-end justify-between gap-8 sm:mb-12"><div><p class="text-xs font-bold tracking-[.24em] text-amber-700">CURATED FOR YOU</p><h2 class="font-display mt-3 text-4xl font-semibold sm:text-5xl">Shop favourites</h2></div><p class="hidden max-w-xs text-sm leading-6 text-stone-500 sm:block">Small details. Better days. Discover pieces chosen with care.</p></div><div class="product-grid grid gap-x-5 gap-y-10 sm:grid-cols-2 lg:grid-cols-4">@foreach($products as $product)<article class="product-card reveal group"><div class="product-media relative aspect-[4/4.7] overflow-hidden rounded-xl bg-stone-100"><img src="{{ $product['image'] }}" alt="{{ $product['name'] }}" loading="lazy" class="h-full w-full object-cover transition duration-700"><span class="absolute left-3 top-3 rounded-full bg-white/90 px-2.5 py-1 text-[9px] font-bold uppercase tracking-[.14em] shadow-sm backdrop-blur">{{ $product['category'] }}</span><button data-add="{{ $product['id'] }}" class="quick-add absolute bottom-3 left-3 right-3 translate-y-3 rounded-full bg-[#081426] py-3 text-xs font-bold text-white opacity-0 transition duration-300 group-hover:translate-y-0 group-hover:opacity-100 focus:translate-y-0 focus:opacity-100">Add to bag</button></div><div class="mt-3.5"><div class="flex items-start justify-between gap-3"><h3 class="min-w-0 font-semibold leading-5">{{ $product['name'] }}</h3><p class="whitespace-nowrap text-sm font-bold">৳{{ number_format($product['price']) }}</p></div><div class="mt-1.5 flex items-center justify-between gap-3"><p class="text-xs text-stone-500">Ready to dispatch</p>@if($product['old_price'])<s class="text-xs text-stone-400">৳{{ number_format($product['old_price']) }}</s>@endif</div></div><button data-add="{{ $product['id'] }}" class="mobile-add mt-3 w-full rounded-full border border-stone-300 py-2.5 text-sm font-bold sm:hidden">Add to bag</button></article>@endforeach</div></div></section>
    <section id="story" class="bg-[#081426] py-24 text-white"><div class="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><div class="reveal"><p class="text-xs font-bold tracking-[.24em] text-amber-200">WHY SHOP WITH US</p><h2 class="font-display mt-4 text-5xl font-semibold sm:text-6xl">Good choices,<br>delivered simply.</h2></div><div class="grid gap-7 sm:grid-cols-2"><div><span class="text-2xl">✦</span><h3 class="mt-3 font-semibold">Quality first</h3><p class="mt-2 text-sm leading-6 text-amber-50/70">Every item is checked before it leaves us.</p></div><div><span class="text-2xl">↗</span><h3 class="mt-3 font-semibold">Fast delivery</h3><p class="mt-2 text-sm leading-6 text-amber-50/70">Reliable shipping throughout Bangladesh.</p></div><div><span class="text-2xl">♡</span><h3 class="mt-3 font-semibold">Real support</h3><p class="mt-2 text-sm leading-6 text-amber-50/70">Message our Facebook page whenever you need help.</p></div><div><span class="text-2xl">✓</span><h3 class="mt-3 font-semibold">Easy ordering</h3><p class="mt-2 text-sm leading-6 text-amber-50/70">Checkout in seconds and pay on delivery.</p></div></div></div></section>
</main>
<footer class="bg-[#050914] py-12 text-white"><div class="mx-auto flex max-w-7xl flex-col gap-7 px-5 sm:flex-row sm:items-end sm:justify-between lg:px-8"><div><div class="flex items-center gap-4"><img src="{{ config('store.logo') }}" alt="Al-Nas logo" class="h-20 w-20 rounded-full object-cover ring-1 ring-[#c8a34f]/50"><div><p class="font-display text-2xl font-bold tracking-[.16em]">{{ config('store.name') }}</p><p class="mt-1 text-xs uppercase tracking-[.18em] text-[#c8a34f]">{{ config('store.tagline') }}</p></div></div><p class="mt-3 text-sm text-white/50">Curated essentials. Delivered with care.</p></div><div class="flex flex-col gap-3 text-sm sm:items-end"><a href="{{ route('store.track') }}" class="underline underline-offset-4">Track your order</a><a href="{{ config('store.facebook') }}" target="_blank" rel="noopener" class="underline underline-offset-4">Follow us on Facebook ↗</a></div></div></footer>

<div id="cart-backdrop" data-close-cart class="fixed inset-0 z-40 hidden bg-black/40 backdrop-blur-sm"></div>
<aside id="cart-drawer" class="drawer fixed right-0 top-0 z-50 flex h-full w-full max-w-md translate-x-full flex-col bg-[#faf9f6] p-6 shadow-2xl"><div class="flex items-center justify-between"><h2 class="font-display text-3xl font-semibold">Your bag</h2><button data-close-cart class="grid h-10 w-10 place-items-center rounded-full border text-xl">×</button></div><div id="cart-empty" class="my-auto text-center"><p class="font-display text-3xl">Your bag is empty</p><p class="mt-2 text-sm text-stone-500">Add something beautiful.</p></div><div id="cart-items" class="mt-8 flex-1 space-y-5 overflow-y-auto"></div><div class="border-t pt-5"><div class="flex justify-between text-lg font-bold"><span>Subtotal</span><span id="cart-subtotal">৳0</span></div><p class="mt-2 text-xs text-stone-500">Delivery fee is calculated at checkout.</p><button id="checkout-button" class="mt-5 w-full rounded-full bg-[#081426] py-4 font-bold text-white disabled:opacity-40">Proceed to checkout</button></div></aside>

<div id="checkout-modal" class="fixed inset-0 z-[60] hidden overflow-y-auto bg-black/50 p-4 backdrop-blur-sm"><div data-close-checkout class="absolute inset-0"></div><div class="relative mx-auto my-8 max-w-xl rounded-[2rem] bg-white p-6 sm:p-9"><button data-close-checkout class="absolute right-5 top-5 text-2xl">×</button><p class="text-xs font-bold tracking-[.2em] text-amber-700">CASH ON DELIVERY</p><h2 class="font-display mt-2 text-4xl font-semibold">Complete your order</h2><p class="mt-2 text-sm text-stone-500">We will call you to confirm before dispatch.</p>@if($errors->any())<div class="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif<form id="checkout-form" action="{{ route('store.checkout') }}" method="POST" class="mt-7 space-y-4">@csrf<input type="hidden" name="items" id="checkout-items"><label class="block text-sm font-semibold">Full name<input name="name" required value="{{ old('name') }}" class="mt-2 w-full rounded-xl border border-stone-300 px-4 py-3 font-normal outline-none focus:border-amber-700"></label><label class="block text-sm font-semibold">Phone number<input name="phone" required value="{{ old('phone') }}" placeholder="01XXXXXXXXX" class="mt-2 w-full rounded-xl border border-stone-300 px-4 py-3 font-normal outline-none focus:border-amber-700"></label><label class="block text-sm font-semibold">Delivery address<textarea name="address" required rows="3" class="mt-2 w-full rounded-xl border border-stone-300 px-4 py-3 font-normal outline-none focus:border-amber-700">{{ old('address') }}</textarea></label><div><p class="mb-2 text-sm font-semibold">Delivery area</p><div class="grid grid-cols-2 gap-3"><label class="rounded-xl border p-3 text-sm"><input type="radio" name="area" value="inside" checked> Inside Chittagong · ৳70</label><label class="rounded-xl border p-3 text-sm"><input type="radio" name="area" value="outside"> Outside Chittagong · ৳130</label></div></div><button class="w-full rounded-full bg-[#081426] py-4 font-bold text-white">Place order</button></form></div></div>
<script>window.storeProducts = @json($products); @if($errors->any()) document.addEventListener('DOMContentLoaded',()=>document.querySelector('#checkout-modal').classList.remove('hidden')); @endif</script>
</body></html>
